---@alias ViewLayout 'horizontal'|'vertical'
---@alias ReviewView 'side_by_side'|'inline'
---@class SetupOptions
---@field layout ViewLayout|nil
---@field view ReviewView|nil
---@class Config
---@field layout ViewLayout
---@field view ReviewView
